include ../../tutorials.mk

## dash-minimal: run minimal Dash app
dash-minimal:
	python dash-minimal.py

## load-css: run CSS loading server
load-css:
	flask --app load-css run

## observe-wrong-simple: simple test of observer/observable done wrong
observe-wrong-simple:
	python observe_wrong.py simple

## observe-wrong-circular: circularity test of observer/observable done wrong
observe-wrong-circular:
	python observe_wrong.py circular

## observe-wrong-multi: test multi-notification of observer/observable done wrong
observe-wrong-multi:
	python observe_wrong.py multi
