include ../tutorials.mk

## dash-minimal: run minimal Dash app
dash-minimal:
	python dash-minimal.py

## dom-demo: run demo of dom.py
dom-demo:
	python dom.py

## load-css: run CSS loading server
load-css:
	flask --app load-css run
