include ../../tutorials.mk

## colors: run colors server
colors:
	SEED=98765 flask --app colors run

## counter: run counter server
counter:
	flask --app counter run

## hello-world: run hello-world server
hello-world:
	flask --app hello-world run
